### ISSUE TITLE
Date of issue should have correct limits

### ISSUE THREAD

**Issue by mtbitcr** [BitcreditProtocol/E-Bills#19]
On the Issue page, you can select a date earlier than today in the date of issue field. This should not happen.
Also, the maximum date must be a maximum of 3 months from today.
![image](https://github.com/BitcoinCredit/E-Bills/assets/57773598/2c4848c9-4fb3-4e50-bb28-281aefbe030b)

**Comment by MykytaTymko** [comment]
On the Issue page, you can select a date earlier than today in the date of issue field. This should not happen.
Also, the maximum date must be a maximum of 3 months from today.
